### ISSUE TITLE
Hack OpenWrt

### ISSUE THREAD

**Issue by pexcn** [openwrt-dev/openwrt#1]
### TODO

- [ ] remove luci-compat
- [ ] WolfSSL Hardware Acceleration && Include ECC Curve 25519 support
- [ ] cake vs fq-pie (cake seems best)
- [ ] https://github.com/openwrt/openwrt/pull/16786/files#diff-e8497a5bb53e37643f8ebbf0e198e283df5ebfa38d43f7dbfff22c44c7b015bbR1497

**Comment by pexcn** [comment]
### TODO

- [ ] adkill
- [ ] adblock
- [ ] simple-adblock
- [ ] pdnsd
- [ ] axel
- [ ] aria2
- [ ] aria2-webui
- https://github.com/openwrt-dev/packages



### master branch

```
make kernel_menuconfig -> generic/config
```

**Comment by pexcn** [comment]
https://github.com/lede-dev ->https://github.com/openwrt-dev
https://travis-ci.org/lede-dev ->https://travis-ci.org/openwrt-dev
GitHub tokens

**Comment by pexcn** [comment]
```
### Kernel driver select for WiFi AP 2.4GHz
### 2.7 = MT7620 v2.7.2.0
### 3.0 = MT7620 v3.0.4.0
CONFIG_FIRMWARE_WIFI2_DRIVER=2.7

### Kernel driver select for WiFi AP 5GHz
### 3.0 = MT7612E v3.0.4.0
CONFIG_FIRMWARE_WIFI5_DRIVER=3.0
```

**Comment by pexcn** [comment]
enable debug option to check tcp fast open is working?

**Comment by pexcn** [comment]
MPTCP

**Comment by pexcn** [comment]
dnsmasq fast lookup: https://github.com/infinet/dnsmasq

**Comment by pexcn** [comment]
Remove SFE if ar71xx support kernel 4.14(offload): http://www.right.com.cn/forum/thread-309841-1-1.html

**Comment by pexcn** [comment]
Refactor [update version display](https://github.com/openwrt-dev/openwrt/commit/3cbda33b50b7d91e57aca1d581411cb1ad8f1a5b)

**Comment by pexcn** [comment]
### Deprecated

```bash
# SFE: on boot
echo 1 > /sys/fast_classifier/skip_to_bridge_ingress
```

**Comment by pexcn** [comment]
多余了？https://github.com/openwrt-dev/openwrt/blob/openwrt-18.06/package/kernel/linux/files/sysctl-tcp-bbr.conf

**Comment by pexcn** [comment]
### kernel 4.14 flow offload

- http://www.right.com.cn/forum/thread-309841-1-1.html

```bash
CONFIG_DEFAULT_kmod-ipt-offload=y
CONFIG_PACKAGE_kmod-ipt-offload=y
CONFIG_PACKAGE_kmod-nft-offload=y

CONFIG_PACKAGE_kmod-nf-flow=y

CONFIG_PACKAGE_kmod-nft-core=y
CONFIG_PACKAGE_kmod-nft-nat=y
CONFIG_PACKAGE_kmod-nft-nat6=y
```

**Comment by pexcn** [comment]
TODO: use new way set ulimit.

**Comment by pexcn** [comment]
### Deprecated (included in original version)

Tweak kernel configs:
```patch
+CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y
+# CONFIG_CC_OPTIMIZE_FOR_SIZE is not set

+CONFIG_OPTIMIZE_INLINING=y
```

```bash
# check
cat build_dir/target-*/linux-*/linux-*/.config | grep OPTIMIZE
```

**Comment by pexcn** [comment]
### Legacy Code

- Add MPTCP: https://github.com/openwrt-dev/openwrt/commit/b054b088ae5e8d4e5b73445c11ed3bf977140b8e https://github.com/openwrt-dev/openwrt/commit/5d7a6bc03de673ef66d6918b4733c92b22720de5

**Comment by pexcn** [comment]
```bash
# 741
# TODO: cat /proc/mtd
```

```bash
# 841
mtd0: 00020000 00010000 "u-boot"
mtd1: 00189420 00010000 "kernel"
mtd2: 00e46be0 00010000 "rootfs"
mtd3: 00a50000 00010000 "rootfs_data"
mtd4: 00010000 00010000 "art"
mtd5: 00fd0000 00010000 "firmware"

Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/root                 4096      4096         0 100% /rom
tmpfs                    29572        68     29504   0% /tmp
/dev/mtdblock3           10560       424     10136   4% /overlay
overlayfs:/overlay       10560       424     10136   4% /
tmpfs                      512         0       512   0% /dev
```

```bash
# 941
mtd0: 00020000 00010000 "u-boot"
mtd1: 00170634 00010000 "kernel"
mtd2: 00e5f9cc 00010000 "rootfs"
mtd3: 00a70000 00010000 "rootfs_data"
mtd4: 00010000 00010000 "art"
mtd5: 00fd0000 00010000 "firmware"

Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/root                 4096      4096         0 100% /rom
tmpfs                    29808       616     29192   2% /tmp
/dev/mtdblock3           10688      2488      8200  23% /overlay
overlayfs:/overlay       10688      2488      8200  23% /
tmpfs                      512         0       512   0% /dev
```

**Comment by pexcn** [comment]
CONFIG_JSON_OVERVIEW_IMAGE_INFO

**Comment by pexcn** [comment]
Really need?
```patch
root@ARCH ~/openwrt # git show 938d56e43073a310271677664dc7d05133ff37eb
commit 938d56e43073a310271677664dc7d05133ff37eb
Author: pexcn <i@pexcn.me>
Date:   2019-07-08 16:20:03 +0800

    enable openssl threading support

diff --git a/package/libs/openssl/Makefile b/package/libs/openssl/Makefile
index eb267f31f0..42bd23bdc0 100644
--- a/package/libs/openssl/Makefile
+++ b/package/libs/openssl/Makefile
@@ -94,7 +94,8 @@ $(call Package/openssl/Default)
   DEPENDS:=+OPENSSL_WITH_COMPRESSION:zlib \
           +OPENSSL_ENGINE_BUILTIN_AFALG:kmod-crypto-user \
           +OPENSSL_ENGINE_BUILTIN_DEVCRYPTO:kmod-cryptodev \
-          +OPENSSL_ENGINE_BUILTIN_PADLOCK:kmod-crypto-hw-padlock
+          +OPENSSL_ENGINE_BUILTIN_PADLOCK:kmod-crypto-hw-padlock \
+          +libpthread
   TITLE+= (libraries)
   ABI_VERSION:=1.1
   MENU:=1
@@ -186,6 +187,9 @@ endef

 OPENSSL_OPTIONS:= shared

+# Enable threading
+OPENSSL_OPTIONS += threads
+
 ifndef CONFIG_OPENSSL_WITH_BLAKE2
   OPENSSL_OPTIONS += no-blake2
 endif
```
